# -*- coding: utf-8 -*-
"""PrimeiraAula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLKLSbwgrb7S8iBBZtv1NFGZOD9Od5t1
"""

A = 20
B=14
print(A+B)

C = A/B
print("C: ",C)

r = [15,21,11,19,21,7]
for num in r:
  sum =+ num

print(sum/6)

import numpy as np
import matplotlib.pyplot as plt

r = np.array(r)
r.mean()

#Gráfico de pontos
plt.plot(r,"x",color="blue")
plt.axhline(y = r.mean())
plt.show()